### PR TITLE
Introduce CommandHandler.js and enhance command functionality

### PR DESCRIPTION
**Pull request by vlazic**
Below is a detailed summary of the changes made for the PR:

1. **Refactoring and File Changes**:
   - A new file, `CommandHandler.js`, has been introduced. This file consolidates all operations related to command execution and display.
   - The `Commands.js` file now solely contains command definitions.
   - The `UI.js` file has undergone refactoring, with its content now wrapped within a class for improved readability.

2. **New Features**:
   - A `HELP` command has been added. This command displays a list of all available commands along with their descriptions.
   - There's a new capability to display multiline command results. This was primarily developed for the `HELP` command but can now be utilized for other commands as well.
   - The display dimensions (both vertical and horizontal) for a command's result are dynamically determined based on the content.

3. **Performance and Code Clean-Up**:
   - In the `Engine.js` file, all references to HTML elements have been centralized. This ensures the `getElementByID` method isn't called repeatedly throughout the game, enhancing performance and readability.

**Suggestion for Future Iterations**:
   - Global variables, mainly defined in `Engine.js`, are potential area of concern. They are generally considered bad practice.

### CODE REVIEW

**Comment by Glowstick0017** [comment]
Hi @vlazic, the modularity is extremely nice for the commands, however while testing the changes, I noticed the color command no longer works and the alias 'tp' for the teleport command does not work. Can you please look into this? Thank you.

**Comment by Glowstick0017** [comment]
@vlazic  it looks like aliased commands display the commands multiple times in the help command.

**Comment by Glowstick0017** [comment]
I also noticed with the Ui.js changes, the activity of the context menu acts strangely

**Comment by vlazic** [comment]
@Glowstick0017 both things should be fixed now

**Review by Glowstick0017 — APPROVED** [review]

**Pull request merged**
